name: Crave Builder(self-hosted)
on:
  workflow_dispatch:
    inputs:
      BASE_PROJECT:
        description: 'Choose a base project:'
        required: true
        default: 'LineageOS 20.0'
        type: choice
        options:
          - 'LineageOS 20.0'
          - 'LineageOS 21.0'
          - 'ArrowOS 13.1'
          - 'DerpFest 13.0'
          - 'CipherOS 14'
          - 'PixelOS 14'
          - 'LineageOS 16.0'
          - 'CyanogenMOD 14.1'
      LOCAL_MANIFEST:
        description: "Personal local manifest [repository or raw]:"
        required: true
        default: 'https://github.com/sounddrill31/local_manifests'
      LOCAL_MANIFEST_BRANCH:
        description: "Personal local manifest's branch:"
        required: false
        default: 'lineage-oxygen'
      DEVICE_NAME:
        description: "Device's codename:"
        required: true
        default: "oxygen"
      PRODUCT_NAME:
        description: "Product to build:"
        required: true
        default: "lineage_oxygen"
      BUILD_COMMAND:
        description: 'Command to be used for compiling:'
        required: true
        default: 'mka bacon'
      BUILD_TYPE:
        description: 'Type of build:'
        required: true
        default: 'userdebug'
        type: choice
        options: 
        - 'eng'
        - 'userdebug'
        - 'user' 
      CLEAN_BUILD:
        description: 'Build with a clean workspace?'
        required: true
        default: 'no'
        type: choice
        options: 
        - 'yes'
        - 'no'

jobs:
  build:
    timeout-minutes: 720      
    name: Build using foss.crave.io
    runs-on: self-hosted
    steps:
    - name: Set up environment
      run: |
        sudo apt-get update
        sudo apt-get install -y tmux

      # Download and configure 'crave'.
    - name: Configure the 'crave' environment
      run: |
        mkdir ${HOME}/bin/
        curl -s https://raw.githubusercontent.com/accupara/crave/master/get_crave.sh | bash -s --
        mv ${PWD}/crave ${HOME}/bin/
        sudo ln -sf /home/${USER}/bin/crave /usr/bin/crave
        envsubst < ${PWD}/crave.conf.sample >> ${PWD}/crave.conf
        rm -rf ${PWD}/crave.conf.sample
      env:
        CRAVE_USERNAME: ${{ secrets.CRAVE_USERNAME }}
        CRAVE_TOKEN: ${{ secrets.CRAVE_TOKEN }}

    - name: Set-up workspace environment
      run: |
        mkdir -p devspace
        sudo mkdir -p /crave-devspaces
        sudo ln -sf ${PWD}/devspace /crave-devspaces
        sudo chmod 777 /crave-devspaces

    - name: Start compilation through 'crave'
      run: |
        crave devspace -- "if tmux has-session -t ghactions; then 
          echo "Runner is already Running" 
        else 
          tmux kill-session -t ghactions;
          tmux new-session -d -s ghactions 
          tmux send-keys -t ghactions './actions-runner/run.sh' Enter 
          echo "Runner Started"
        fi "

    # Your build steps here...

    - name: Upload to Salesforce
      run: |
        # Replace this command with the one that uploads the zip files to Salesforce
        echo "Uploading zip files to Salesforce..."
